baseURL: "https://rohanpatankar.netlify.app/"
languageCode: "en-us"
title: "Rohan Patankar | Portfolio"
theme: "./.."
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"
  
enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: /images/fav.png
  description: "Rohan's personal portfolio"

  # Navbar Menus
  

  # home
  disable_home: false
  profile_image: /images/profile.png
  name: "Rohan Patankar"
  namecolor: ffc107
  profession: "Aspiring Data Scientist"
  github: "https://github.com/rohanpatankar926/"
  linkedin: "https://www.linkedin.com/in/rohan-patankar-2aa707213/"
  twitter: "https://twitter.com/Rohan20075428"
  gmail: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=rohanpatankar926@gmail.com"
  instagram: "https://instagram.com/__rohan__95?utm_medium=copy_link"
  

  # Custom social links
  customSocialLinks:
    - fontAwesomeIconName: "fa fa-envelope"
      url: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=rohanpatankar926@gmail.com"
      fontAwesomeIconName: "fa fa-envelope"
      url: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=rohanpatankar926@gmail.com"

  # About
  disable_about: false  
  descripe_l1_person: "Hii there! Myself **Rohan** and I am persuing my B.Tech in **DataScience** at **Jain University** having CGPA of **8.88**. I am very passionate about evergrowing technology especially in the field of DataScience and Web Devolopment."
  descripe_l2_person: "### Real world capabilities"
  descripe_l3_person: "I believe Skills are the ability to perform certain tasks well. Some skills can be measured and you acquire them through deliberate effort, others are related to your personality traits. In other words, not all skills are created equal. That’s why we call some of them “hard” and others “soft”.**Hard skills** are the skills that I’ve acquired through deliberate effort. They can be learned, taught, and measured.My hard skills include: **HTML, CSS, Python, SQL, JavaScript, MachineLearning, C and others.**
  **Soft skills**, on the other hand, are closely tied to one’s personality traits. Some of my softskills are **leadership, communication, or other interpersonal skills**. As opposed to hard skills, soft skills cannot be easily taught. Examples of soft skills include: problem-solving, negotiating, multitasking, time management, presenting, and others."
  descripe_l4_person: "*You can find my works [here](#projects)* "

  skills:
    - name: Python
      percentage: 80
    - name: Flask 
      percentage: 80
    - name: Flutter
      percentage: 60
    - name: "HTML"
      percentage: 90
    - name: "CSS"
      percentage: 75
    - name: JavaScript
      percentage: 70
    - name: Machine Learning
      percentage: 80
    - name: Tableu
      percentage: 80
    - name: SQL
      percentage: 80
    - name: Mongodb
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Valuecom-Infosolutions-pvt-ltd"
      role: "Software Developer Intern"
      startdate: "April 07 2022"
      enddate: "Ongoing"
      featuredpoints:
        - point:  "Currently building android and ios application frontend for the company"

    - company: "iNeuron"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Project Intern"
      startdate: "Jan 18 2022"
      enddate: "April 16 2022"
      featuredpoints:
        - point: "Solved an Industry level end to end machine learning project"
        - point: "ML project domain was with respect to Insurance"
        - point: "Used MLOPS(DVC pipeline) for building and deploying the model."
        - point: "Built CI/CD pipeline"
        - point: "Used Flask Api as a backend"
        - point: "Used Github actions for automatic build and deploy of the model"
        - point: "Finally hosted to cloud environment i chose heroku platform."
    - company: "PantechSolutions"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Machine Learning Intern(trainee)"
      startdate: "Sep 2021"
      enddate: "Oct 2021"
      featuredpoints:
        - point: "Learn ML & DL from Scratch"
        - point: "Learnt to build neural networks using ANN,CNN,RNN,LSTM etc"
        - point: "Build numerous types of projects by using different ML and DL algorithms"
    - company: "AzureSkynets_Pvt-Ltd"
      # id: "AzureSkynets Pvt Ltd" // use this, when you want to change the id(used for navigation)
      role: "Python Programming Internship(trainee)"
      startdate: Jan 2020
      enddate: Feb 2020
      featuredpoints:
        - point: "Learnt python programming from basics to classes,objects,OOPS"
        - point: "Learnt libraries like numpy,pandas,matplotlib,seaborn,plotly."
        - point: "Built projects like ML-preprocessor with CLI,Email Slicer and so on"

  # Education
  disable_education: false
  education:
    - degree: "B.tech-"
      branch: "DataScience(HONOURS)"
      university: "Jain University,Bangalore,India"
     
      startedyear: "2019"
      graduation: "2023"
    - degree: "Class XII-"
      branch: "PCMS"
      university: "Vidyodaya PU College"
      startedyear: "2018"
      graduation: "2019"
    - degree: "Class X"
      university: "Indrali English Medium High School"
      startedyear: "2016"
      graduation: "2017"

  # Projects
  disable_projects: false
  projects:
    - name: "Wafer Fault Detection"
      img: /images/progress.jpg
      githublink: "https://github.com/rohanpatankar926/"
      featuredlink: ""
      description: "Currently Working On It Will Update Soon..."
    - name: "Onsite Health Diagnostic"
      img: /images/progress.jpg
      githublink: "https://github.com/rohanpatankar926/"
      featuredlink: ""
      description: "Currently Working On It Will Update Soon..."
    - name: "Insurance Prediction website"
      img: /images/Capture.png
      githublink: "https://github.com/rohanpatankar926/intenship_project"
      featuredlink: "https://drive.google.com/file/d/1bhcdx4hRZ5EBiK-Cg6CH7xdzAzA3Az3E/view?usp=sharing"
      description: "The End-goal of this project is to give people an estimate of how much they need based on their individual health situation.So here I have implemented End-End Machine Learning project using MLOPS lifecycle.Built CI/CD pipeline.DVC(Data Version Control) was used here for track ml model.It was regression problem statement and in order to get best accuracy I have used GradientBoostingRegressor to solve the problem which gave r2_score of 85% after tuning parameters."
    - name: "ML Preprocessor CLI"
      img: /images/ml_pic.png
      githublink: "https://github.com/rohanpatankar926/ml-preprocessor-cli"
      featuredlink: "https://www.crio.do/projects/python-preprocessor-cli/"
      description: "The main objective of this project is You will implement a Command Line Interface (CLI) which will preprocess your dataset and save your time."
  # services
  disable_achievements: false
  achievements:
    - title: "Website Devolopment"
      description: "Design a website for personal use or for business purpose using HTML, CSS, JS and Python."
      img: /images/Website-Design-new.jpg
    - title: Data Analysis
      description: "With the help of tableu or python analyze the data of the business or client needs which help them to solve business problems."
      img: /images/da.jpg
      # url: https://example.com
    - title: Machine Learning & Deep Learning
      description: "Build various types of ML and DL models according to business or client needs in which it helps to solve complex business issues." 
      img: /images/ml.png
    
  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you! 
  email: "rohanpatankar926@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
